name: Puppet Version Bump

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment in the format <region3><client3>_<env3>'
        required: true
      version:
        description: 'Version in format x.y.z.w (separators "." or "-")'
        required: true

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Parse inputs
        shell: bash
        run: |
          # Split environment into region+client and env
          IFS='_' read -r rc env <<< "${{ inputs.environment }}"
          region="${rc:0:3}"
          client="${rc:3:3}"
          echo "REGION=$region" >> $GITHUB_ENV
          echo "CLIENT=$client" >> $GITHUB_ENV
          echo "ENV_NAME=$env" >> $GITHUB_ENV
          echo "VERSION=${{ inputs.version }}" >> $GITHUB_ENV

      - name: Update puppetVersionEnvOverride in client-region-env file
        shell: bash
        run: |
          file="values/$CLIENT/$REGION/$ENV_NAME.yaml"
          if [[ -f "$file" ]]; then
            yq eval -i ".puppetVersionEnvOverride |= with_entries(.value = strenv(VERSION))" "$file"
          fi

      - name: Update puppetVersionEnvOverride in client-env file
        shell: bash
        run: |
          file="values/$CLIENT/$ENV_NAME.yaml"
          if [[ -f "$file" ]]; then
            yq eval -i ".puppetVersionEnvOverride |= with_entries(.value = strenv(VERSION))" "$file"
          fi

      - name: Update puppetVersion in proxy.yaml
        shell: bash
        run: |
          file="values/proxy.yaml"
          if [[ -f "$file" ]]; then
            yq eval -i ".puppetVersion = strenv(VERSION)" "$file"
          fi

      - name: Create branch and push changes
        shell: bash
        run: |
          BRANCH="puppet-version-bump-$REGION-$CLIENT-$ENV_NAME-$VERSION"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b "$BRANCH"
          git add values/proxy.yaml values/$CLIENT/$REGION/$ENV_NAME.yaml values/$CLIENT/$ENV_NAME.yaml || true
          git commit -m "[Minor][FAB-000] Puppet version bump $REGION-$CLIENT-$ENV_NAME-$VERSION"
          git push origin "$BRANCH"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "[Minor][FAB-000] Puppet version bump $REGION-$CLIENT-$ENV_NAME-$VERSION"
          branch: "puppet-version-bump-$REGION-$CLIENT-$ENV_NAME-$VERSION"
          title: "[Minor][FAB-000] Puppet version bump $REGION-$CLIENT-$ENV_NAME-$VERSION"
          body: |
            This PR bumps the Puppet version to `${{ inputs.version }}` for environment `${{ inputs.environment }}`.
